# Custom Caddy with DNS challenge plugin for {{ loco.admin.dns_provider }}
FROM caddy:2-builder AS builder
RUN xcaddy build --with github.com/caddy-dns/{{ loco.admin.dns_provider }}
FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
