---
# roles/apps/vikunja/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart vikunja
  community.docker.docker_compose_v2:
    project_src: "{{ vikunja_stack_path }}"
    state: restarted
