---
# roles/apps/invoiceninja/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart invoiceninja
  community.docker.docker_compose_v2:
    project_src: "{{ invoiceninja_stack_path }}"
    state: restarted
