---
# roles/apps/planka/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart planka
  community.docker.docker_compose_v2:
    project_src: "{{ planka_stack_path }}"
    state: restarted
