---
all:
  hosts:
    loco-master:
      ansible_host: "{{ vault_master_netbird_ip | default('127.0.0.1') }}"
      ansible_user: srvadmin
      ansible_python_interpreter: /usr/bin/python3
      server_roles: [master]
      is_lxc: true
